name: Build
on: [push, pull_request]
env:
  zig_version: 0.13.0

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest, macos-latest]
    
    runs-on: ${{matrix.platform}}
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ env.zig_version }}

      - name: Install Dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update -qq && sudo apt-get install -y libsdl2-*
      
      - name: Install Dependencies on macOS
        if: runner.os == 'macOS'
        run: brew install sdl2 sdl2_mixer sdl2_net sdl2_image sdl2_ttf      

      - name: Build
        - run: zig build -Doptimize=ReleaseSafe
        #- run: zig build test

      - uses: actions/upload-artifact@v2
        with:
          name: DungeonRush-${{ matrix.platform }}
          path: zig-out/bin

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: goto-bus-stop/setup-zig@v1
  #       with:
  #         version: ${{ env.zig_version }}
  #     - run: zig fmt --check zsrc/*.zig