name: Build
on: [push, pull_request]
env:
  zig_version: 0.13.0

jobs:
  build:
    name: "DungeonRush Release - ${{ matrix.os }} ${{ matrix.arch }}"
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: true
      matrix:
        #platform: [macos-latest] #ubuntu-latest, macos-latest]
        os:
          - macOS-13
          - ubuntu-latest
        arch:
          - x64
        include:
          - os: macOS-latest
            arch: arm64 #aarch64
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: ${{ env.zig_version }}

      - name: Install Dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update -qq && sudo apt-get install -y libsdl2-*

      - name: Install Dependencies on macOS
        if: runner.os == 'macOS'
        run: brew install sdl2 sdl2_mixer sdl2_net sdl2_image sdl2_ttf

      - name: Compile with Zig
        run: zig build -Doptimize=ReleaseSafe

      - name: Copy over game resources
        run: |
          mkdir -p zig-out/bin/res
          cp -r res/* zig-out/bin/res/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DungeonRush-${{ matrix.os }}-${{ matrix.arch }}
          path: zig-out/bin

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: goto-bus-stop/setup-zig@v1
  #       with:
  #         version: ${{ env.zig_version }}
  #     - run: zig fmt --check zsrc/*.zig